#pragma once

#include <stdint.h>

/*
 * EasyTVC v0.1 pin map from Brian Wong's ArduPilot hwdef (2026-09-29).
 * Canonical source: board/easytvc.hwdef
 *
 * This header is a lookup table only. Including it does not enable clocks or
 * write GPIO. Keep EASYTVC_PYRO_OUTPUTS_COMPILED_IN at 0 until pyro nets are
 * independently verified; the vendor has not fully tested pyro or continuity.
 *
 * Vendor notes that still apply:
 * - BME280 needs the STM32F4 internal pull-up on its I2C pins (I2C1 in the
 *   hwdef already requests PULLUP on PB6/PB7).
 * - Do not use pyro channels with pyrotechnic loads.
 */

#define EASYTVC_HSE_HZ 16000000U
#define EASYTVC_FLASH_SIZE_KB 1024U

/* ArduPilot custom bootloader reserves 64 KiB. This project's blank image is
 * linked at 0x08000000 for ST ROM DFU, not that bootloader. */
#define EASYTVC_AP_BOOTLOADER_RESERVE_KB 64U

#define EASYTVC_GPIO_PIN(port, pin) ((((uint16_t)(port)) << 8) | (uint16_t)(pin))
#define EASYTVC_GPIO_PORT(id) ((uint8_t)((id) >> 8))
#define EASYTVC_GPIO_PAD(id) ((uint8_t)((id) & 0xFFU))

#define EASYTVC_PORT_A 0U
#define EASYTVC_PORT_B 1U
#define EASYTVC_PORT_C 2U

/* Alternate functions from STM32F405 datasheet, for a later adapter. */
#define EASYTVC_AF_TIM3_TIM4 2U
#define EASYTVC_AF_I2C       4U
#define EASYTVC_AF_SPI1_SPI2 5U
#define EASYTVC_AF_SPI3      6U
#define EASYTVC_AF_USART2    7U
#define EASYTVC_AF_UART4     8U
#define EASYTVC_AF_OTG_FS    10U

/* USB OTG FS */
#define EASYTVC_PIN_USB_DM EASYTVC_GPIO_PIN(EASYTVC_PORT_A, 11U)
#define EASYTVC_PIN_USB_DP EASYTVC_GPIO_PIN(EASYTVC_PORT_A, 12U)

/* SPI1 BMI088: gyro CS PC7, accel CS PC8, Mode 3, 10 MHz */
#define EASYTVC_SPI1_SCK  EASYTVC_GPIO_PIN(EASYTVC_PORT_A, 5U)
#define EASYTVC_SPI1_MISO EASYTVC_GPIO_PIN(EASYTVC_PORT_A, 6U)
#define EASYTVC_SPI1_MOSI EASYTVC_GPIO_PIN(EASYTVC_PORT_A, 7U)
#define EASYTVC_PIN_BMI088_G_CS EASYTVC_GPIO_PIN(EASYTVC_PORT_C, 7U)
#define EASYTVC_PIN_BMI088_A_CS EASYTVC_GPIO_PIN(EASYTVC_PORT_C, 8U)
#define EASYTVC_BMI088_SPI_HZ 10000000U

/* Vendor IMU rotation: ROLL_180_YAW_90. Apply only after a bench check. */
#define EASYTVC_BMI088_ROTATION_ROLL_180_YAW_90 1

/* SPI2 W25Q128JVS, Mode 3, 32 MHz */
#define EASYTVC_SPI2_SCK  EASYTVC_GPIO_PIN(EASYTVC_PORT_B, 13U)
#define EASYTVC_SPI2_MISO EASYTVC_GPIO_PIN(EASYTVC_PORT_B, 14U)
#define EASYTVC_SPI2_MOSI EASYTVC_GPIO_PIN(EASYTVC_PORT_B, 15U)
#define EASYTVC_PIN_FLASH_CS EASYTVC_GPIO_PIN(EASYTVC_PORT_C, 5U)
#define EASYTVC_FLASH_SPI_HZ 32000000U

/* SPI3 microSD */
#define EASYTVC_SPI3_SCK  EASYTVC_GPIO_PIN(EASYTVC_PORT_C, 10U)
#define EASYTVC_SPI3_MISO EASYTVC_GPIO_PIN(EASYTVC_PORT_C, 11U)
#define EASYTVC_SPI3_MOSI EASYTVC_GPIO_PIN(EASYTVC_PORT_C, 12U)
#define EASYTVC_PIN_SD_CS EASYTVC_GPIO_PIN(EASYTVC_PORT_C, 6U)

/* I2C_ORDER I2C1, I2C2  =>  bus 0 = I2C1 (internal), bus 1 = I2C2 */
#define EASYTVC_I2C1_SCL EASYTVC_GPIO_PIN(EASYTVC_PORT_B, 6U)
#define EASYTVC_I2C1_SDA EASYTVC_GPIO_PIN(EASYTVC_PORT_B, 7U)
#define EASYTVC_I2C1_ENABLE_INTERNAL_PULLUP 1

#define EASYTVC_I2C2_SCL EASYTVC_GPIO_PIN(EASYTVC_PORT_B, 10U)
#define EASYTVC_I2C2_SDA EASYTVC_GPIO_PIN(EASYTVC_PORT_B, 11U)
#define EASYTVC_I2C2_ENABLE_INTERNAL_PULLUP 0

/*
 * hwdef probes BMP280 on I2C0 0x76/0x77 and I2C1 0x77. The board is specified
 * as BME280 (chip id 0x60). Probe both 7-bit addresses on I2C1 first.
 */
#define EASYTVC_BME280_I2C_ADDR_PRIMARY   0x76U
#define EASYTVC_BME280_I2C_ADDR_SECONDARY 0x77U

/* ADC1 IN4 battery sense */
#define EASYTVC_PIN_BATT_VOLTAGE_SENS EASYTVC_GPIO_PIN(EASYTVC_PORT_A, 4U)
#define EASYTVC_ADC_BATT_CHANNEL 4U

/* LEDs: OUTPUT LOW at init. Silk: LED0 ACT blue, LED1 B/E green */
#define EASYTVC_PIN_LED_BLUE  EASYTVC_GPIO_PIN(EASYTVC_PORT_B, 5U)
#define EASYTVC_PIN_LED_GREEN EASYTVC_GPIO_PIN(EASYTVC_PORT_B, 4U)
#define EASYTVC_PIN_LED_RED   EASYTVC_GPIO_PIN(EASYTVC_PORT_B, 3U)

/* USART2 telem/GNSS (SERIAL1), UART4 RC (SERIAL2) */
#define EASYTVC_USART2_TX EASYTVC_GPIO_PIN(EASYTVC_PORT_A, 2U)
#define EASYTVC_USART2_RX EASYTVC_GPIO_PIN(EASYTVC_PORT_A, 3U)
#define EASYTVC_UART4_TX  EASYTVC_GPIO_PIN(EASYTVC_PORT_A, 0U)
#define EASYTVC_UART4_RX  EASYTVC_GPIO_PIN(EASYTVC_PORT_A, 1U)
#define EASYTVC_DEFAULT_UART_BAUD 115200U

/* Servo PWM 1..4 */
#define EASYTVC_PIN_PWM1 EASYTVC_GPIO_PIN(EASYTVC_PORT_B, 0U) /* TIM3_CH3 */
#define EASYTVC_PIN_PWM2 EASYTVC_GPIO_PIN(EASYTVC_PORT_B, 1U) /* TIM3_CH4 */
#define EASYTVC_PIN_PWM3 EASYTVC_GPIO_PIN(EASYTVC_PORT_B, 8U) /* TIM4_CH3 */
#define EASYTVC_PIN_PWM4 EASYTVC_GPIO_PIN(EASYTVC_PORT_B, 9U) /* TIM4_CH4 */

#define EASYTVC_PWM1_TIM 3U
#define EASYTVC_PWM1_CH  3U
#define EASYTVC_PWM2_TIM 3U
#define EASYTVC_PWM2_CH  4U
#define EASYTVC_PWM3_TIM 4U
#define EASYTVC_PWM3_CH  3U
#define EASYTVC_PWM4_TIM 4U
#define EASYTVC_PWM4_CH  4U

/*
 * Pyro outputs default LOW with pulldown. PA13 is SWDIO and PA14 is SWCLK;
 * configuring them as GPIO takes SWD away. Do not initialize these pins in
 * bring-up firmware.
 */
#define EASYTVC_PIN_PYRO1_OUT EASYTVC_GPIO_PIN(EASYTVC_PORT_B, 2U)
#define EASYTVC_PIN_PYRO2_OUT EASYTVC_GPIO_PIN(EASYTVC_PORT_A, 13U)
#define EASYTVC_PIN_PYRO3_OUT EASYTVC_GPIO_PIN(EASYTVC_PORT_C, 3U)
#define EASYTVC_PIN_PYRO1_CONT EASYTVC_GPIO_PIN(EASYTVC_PORT_B, 12U)
#define EASYTVC_PIN_PYRO2_CONT EASYTVC_GPIO_PIN(EASYTVC_PORT_C, 4U)
#define EASYTVC_PIN_PYRO3_CONT EASYTVC_GPIO_PIN(EASYTVC_PORT_C, 2U)

#define EASYTVC_PIN_BUZZER EASYTVC_GPIO_PIN(EASYTVC_PORT_A, 8U)
#define EASYTVC_PIN_DFU    EASYTVC_GPIO_PIN(EASYTVC_PORT_A, 14U)
