set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

if(DEFINED ENV{ARM_TOOLCHAIN_DIR})
    set(ARM_TOOL_PREFIX "$ENV{ARM_TOOLCHAIN_DIR}/bin/arm-none-eabi-")
else()
    set(ARM_TOOL_PREFIX "arm-none-eabi-")
endif()
set(CMAKE_C_COMPILER "${ARM_TOOL_PREFIX}gcc")
set(CMAKE_ASM_COMPILER "${ARM_TOOL_PREFIX}gcc")
set(CMAKE_OBJCOPY "${ARM_TOOL_PREFIX}objcopy")
set(CMAKE_SIZE "${ARM_TOOL_PREFIX}size")

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
